version: '3'

networks:
  net:

services:
  cache:
    image: eve
    command: ["/go/src/github.com/rvflash/eve/server/tcp/tcp", "-port", "9090", "-from", "http://app:8080/vars"]
    ports:
      - 9090:9090
    depends_on:
      - app
    networks:
      - net
  app:
    build: .
    image: eve
    volumes:
      - ./testdata:/go/src/github.com/rvflash/eve/testdata
    command: [
      "/go/src/github.com/rvflash/eve/server/http/http",
      "-port", "8080",
      "-dsn", "/go/src/github.com/rvflash/eve/testdata/beta.db"
    ]
    ports:
      - 8080:8080
    networks:
      - net